/*
 * Copyright (C) 2007, 2008, Apple Inc. All rights reserved.
 *
 * No license or rights are granted by Apple expressly or by implication,
 * estoppel, or otherwise, to Apple copyrights, patents, trademarks, trade
 * secrets or other rights.
 */

module css {

    interface [
            AppleCopyright,
            GenerateConstructor,
            HasIndexGetter]
    WebKitCSSTransformValue : CSSValueList {

        // OperationTypes
        const unsigned short CSS_UNKNOWN     = 0;
        const unsigned short CSS_MATRIX      = 1;
        const unsigned short CSS_MATRIX3D    = 2;
        const unsigned short CSS_ROTATE      = 3;
        const unsigned short CSS_ROTATE3D    = 4;
        const unsigned short CSS_TRANSLATE   = 5;
        const unsigned short CSS_TRANSLATE3D = 6;
        const unsigned short CSS_SCALE       = 7;
        const unsigned short CSS_SCALE3D     = 8;
        const unsigned short CSS_SKEWX       = 9;
        const unsigned short CSS_SKEWY       = 10;
        const unsigned short CSS_SKEWZ       = 11;
        const unsigned short CSS_PERSPECTIVE = 12;
        const unsigned short CSS_ROTATEX     = 13;
        const unsigned short CSS_ROTATEY     = 14;
        const unsigned short CSS_ROTATEZ     = 15;
        const unsigned short CSS_TRANSLATEX  = 16;
        const unsigned short CSS_TRANSLATEY  = 17;
        const unsigned short CSS_TRANSLATEZ  = 18;
        const unsigned short CSS_SCALEX      = 19;
        const unsigned short CSS_SCALEY      = 20;
        const unsigned short CSS_SCALEZ      = 21;

        readonly attribute unsigned short operationType;
    };

}
