/*
 * Copyright (C) 2007, 2008, Apple Inc. All rights reserved.
 *
 * No license or rights are granted by Apple expressly or by implication,
 * estoppel, or otherwise, to Apple copyrights, patents, trademarks, trade
 * secrets or other rights.
 */

module events {

interface WebKitTransitionEvent : Event {
     readonly attribute DOMString          propertyName;
     readonly attribute double             elapsedTime;
     void               initWebKitTransitionEvent(in DOMString typeArg,
                                           in boolean canBubbleArg,
                                           in boolean cancelableArg,
                                           in DOMString propertyNameArg,
                                           in double elapsedTimeArg);
};

}
